/* Automatically generated by './build/bin/build-entry.js' */
import HkFallingwaterWarning from './park-warning/index.js'
import HkmultiScreen from './multi-screen/index.js'
import HksingleScreen from './single-screen/index.js'
import HkvideoPlayback from './video-playback/index.js'
import HkfourSplitScreen from './four-split-screen/index.js'
import carousel from './carousel/src/main'
import carouselItem from './carousel/src/item'
import slider from './slider'

const components = [
  HkFallingwaterWarning,
  HkmultiScreen,
  HksingleScreen,
  HkvideoPlayback,
  HkfourSplitScreen,
  carousel,
  carouselItem,
  slider
]

const install = function (Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return

  components.map(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.0',
  install,
  HkFallingwaterWarning,
  HkmultiScreen,
  HksingleScreen,
  HkvideoPlayback,
  HkfourSplitScreen,
  carousel,
  carouselItem,
  slider
}
